// utils/paymentHistoryData.ts

import type { PaymentHistory } from "./types";

export const paymentHistoryData: PaymentHistory[] = [
  {
    doctorName: "Isabel Wiza",
    doctorImg: "/assets/images/avatar-1.png",
    email: "alinamath@gmail.com",
    mobile: "+91 8805322849",
    withdrawalAmount: "4,290",
    requestedDate: "1 Feb 2024",
    walletAmount: "30,000",
    status: "Paid",
    approvalDate: "1st October, 2023",
  },
  {
    doctorName: "Soumya Maheswari",
    doctorImg: "/assets/images/avatar-2.png",
    email: "alinamath@gmail.com",
    mobile: "+91 8805322849",
    withdrawalAmount: "5,290",
    requestedDate: "1 Feb 2024",
    walletAmount: "30,000",
    status: "Decline",
    approvalDate: "2nd July, 2023",
  },
  {
    doctorName: "Margie O'Reilley",
    doctorImg: "/assets/images/avatar-3.png",
    email: "alinamath@gmail.com",
    mobile: "+91 8805322849",
    withdrawalAmount: "4,290",
    requestedDate: "1 Feb 2024",
    walletAmount: "30,000",
    status: "Decline",
    approvalDate: "4th November, 2023",
  },
  {
    doctorName: "Lucas Legros",
    doctorImg: "/assets/images/avatar-4.png",
    email: "alinamath@gmail.com",
    mobile: "+91 8805322849",
    withdrawalAmount: "4,290",
    requestedDate: "1 Feb 2024",
    walletAmount: "30,000",
    status: "Decline",
    approvalDate: "4th November, 2023",
  },
  {
    doctorName: "Shanelle Ziemann",
    doctorImg: "/assets/images/avatar-1.png",
    email: "alinamath@gmail.com",
    mobile: "+91 8805322849",
    withdrawalAmount: "5,290",
    requestedDate: "1 Feb 2024",
    walletAmount: "30,000",
    status: "Paid",
    approvalDate: "5th December, 2023",
  },
  {
    doctorName: "William Stephan",
    doctorImg: "/assets/images/avatar-2.png",
    email: "alinamath@gmail.com",
    mobile: "+91 8805322849",
    withdrawalAmount: "5,290",
    requestedDate: "1 Feb 2024",
    walletAmount: "30,000",
    status: "Paid",
    approvalDate: "5th December, 2023",
  },
  {
    doctorName: "Smith Birkin",
    doctorImg: "/assets/images/avatar-3.png",
    email: "alinamath@gmail.com",
    mobile: "+91 8805322849",
    withdrawalAmount: "5,290",
    requestedDate: "1 Feb 2024",
    walletAmount: "30,000",
    status: "Paid",
    approvalDate: "5th December, 2023",
  },
];
